import React from 'react'
import ProductListing from '../Components/ProductListing'

export const metadata = {
  title: "Categories | Ecommerce Website",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <ProductListing/>
    </>
  )
}
