"use client"
import ProductDetails from '@/app/Components/ProductDetails';
import ProductListing from '@/app/Components/ProductListing'
import { useParams } from 'next/navigation'
import React from 'react'

export const metadata = {
  title: "Categories | Ecommerce Website",
  description: "Generated by create next app",
};

export default function page() {

    const params = useParams();

  return (
    <>
        {
            params.category_slug[1]
            ?
            <ProductDetails/>
            :
            <ProductListing/>
        }
      
    </>
  )
}
